/*
 * This source file was generated by the Gradle 'init' task
 */
package hoc.unam
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


fun main() {
    val graphFilePath: String = "/home/mexidis/development/mintree/files/input.txt"

    try {
        // 1. Leer y construir la gráfica desde el archivo
        val graph = GraphReader.readFromFile(graphFilePath)
        println(graph)

        // 2. Encontrar el Árbol Generador de Peso Mínimo (MST)
        //println("\n2. Calculando el Árbol Generador de Peso Mínimo (MST) usando Kruskal...")
        // val kruskal = KruskalMST<String>()
        // val mst = kruskal.findMST(graph)
        // val totalWeight = mst.edges.sumOf { it.weight }

        // println("MST:")
        // println(mst)
        // println("Peso total del MST: $totalWeight")

    } catch (e: Exception) {
        System.err.println("Ocurrio un error: ${e.message}")
    }
}
