/*
 * This source file was generated by the Gradle 'init' task
 */
package hoc.unam

import java.io.IOException

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


fun main() {
    val graphFilePath: String = "files/input.txt"

    try {
        val reader = FileReaderToGraph(graphFilePath)

        val myGraph = reader.createGraphFromFile()


        val distance_a_b = myGraph.getDistance("a", "b")
        println(distance_a_b)

        val distance_f_g = myGraph.getDistance("f", "g")
        println(distance_f_g) // Debería ser 11.0

        myGraph.printMatrix()

    } catch (e: IOException) {
        // Este bloque se ejecutará si el archivo no se encuentra
        System.err.println("Error al leer el archivo: ${e.message}")
    } catch (e: Exception) {
        // Para cualquier otro error inesperado
        System.err.println("Ocurrió un error inesperado: ${e.message}")
    }
}

// TODO Calcular Floy-Warshall
// TODO completar la gráfica
// TODO crear el normalizador
// TODO hacer la función de costo
