/*
 * This source file was generated by the Gradle 'init' task
 */
package hoc.unam

import java.io.IOException

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


fun main(args: Array<String>) {
    val graphFilePath = args[0]
    val k = args[1].toInt()
    try {
        val reader = FileReaderToGraph(graphFilePath,k)

        val myGraph = reader.createGraphFromFile()


        val distance_a_b = myGraph.getDistance("a", "b")
        println(distance_a_b)

        val distance_f_g = myGraph.getDistance("f", "g")
        println(distance_f_g) // Debería ser 11.0

        myGraph.printGraphMatrix(MatrixType.ADJACENCY)
        myGraph.completeGraph()
        val shortestPaths = myGraph.getAdjMatShortestPaths()
        // Imprimir la matriz de resultados
        myGraph.printGraphMatrix(MatrixType.SHORTEST_PATHS)


        myGraph.printGraphMatrix(MatrixType.COMPLETED)


        val kNodes = 4 // Queremos un MST que conecte 4 nodos (3 aristas)

        println("\n--- Ejecutando el Algoritmo de Prim (K=$kNodes MST) ---")
        val totalMstCost = myGraph.primsAlgorithm(kNodes)
        println("-------------------------------------------------------")
        println("Costo Total del MST de $kNodes nodos: ${"%.2f".format(totalMstCost)}")
        println("-------------------------------------------------------")


        myGraph.printGraphMatrix(MatrixType.MST)

    } catch (e: IOException) {
        System.err.println("Error al leer el archivo:\n ${e.message}")
    } catch (e: Exception) {
        System.err.println(e.message)
    }
}

// TODO hacer la función de costo
